# install scripts
brew 'wget'
brew 'rbenv'
brew 'postgresql'
brew 'maven'
brew 'memcached'
brew 'libxml2'
brew 'mysql'

# get brew cask for apps
tap 'caskroom/cask'
tap 'caskroom/homebrew-versions'

# install the apps
cask 'google-chrome'
cask 'firefox'
cask 'java' unless system "/usr/libexec/java_home --failfast"
cask 'iterm2'
cask 'slack'
cask 'sequel-pro'
